development:
  host: localhost
  adapter: postgresql
  database: search_demo_dev
  pool: 5
  username: postgres
  password: root
  min_messages: warning

production:
  adapter: postgresql
  database: search_demo_pro
  pool: 5
  username: postgres
  password: root
  min_messages: warning

test:
  host: localhost
  adapter: postgresql
  database: search_demo_test
  pool: 5
  username: postgres
  password: root
  min_messages: warning
